name: Build x64 Release for Windows

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-x64-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download git submodules
        run: git submodule update --init --recursive

      - name: Use Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -S . --preset x64-windows-rel

      - name: Build
        run: cmake --build build/x64-windows-rel --target all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            out/Release/**/*.exe
            out/Release/**/*.dll
            assets/