name: Build x64 Release for Windows

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S . -B build/x64-release --preset x64-release

      - name: Build and install
        run: cmake --build build/x64-release --target install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            out/**/*.exe
            out/**/*.dll
            out/assets/