name: Build x64 Release

on: [pull_request, workflow_dispatch]

jobs:
  windows-x64:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Use Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -S . --preset x64-windows-rel
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - name: Build
        run: cmake --build build\x64-windows-rel --target Anisette --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x64-windows-release
          path: |
            build/x64-windows-rel/bin/Release/

  linux-x64:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install packages
        run: sudo apt-get install -y cmake ninja-build

      - name: Configure CMake
        run: cmake -S . --preset x64-linux-rel
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - name: Build
        run: cmake --build build/x64-linux-rel --target Anisette --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x64-linux-release
          path: |
            build/x64-linux-rel/bin/Anisette
            build/x64-linux-rel/bin/**/*.so

  osx-x64:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
    
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install CMake
        run: brew install cmake ninja pkg-config

      - name: Configure CMake
        run: cmake -S . --preset x64-osx-rel
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - name: Build
        run: cmake --build build/x64-osx-rel --target Anisette --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x64-osx-release
          path: |
            build/x64-osx-rel/bin/Anisette
            build/x64-osx-rel/bin/**/*.dylib
